# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
palette:
  # rose pine moon
  foam: "#9ccfd8"
  gold: "#f6c177"
  iris: "#c4a7e7"
  love: "#eb6f92"
  moon: "#ea9a97"
  pine: "#3e8fb0"
  subtle: "#908caa"
  text: "#e0def4"
transient_prompt:
  background: transparent
  foreground: "p:text"
  template: " âˆ‡ "
blocks:
  - alignment: left
    type: prompt
    segments:
      - type: os
        template: " {{ .Icon }} "
        foreground: "p:subtle"
        style: plain
      - type: session
        style: "plain"
        foreground: "p:subtle"
        template: "{{ .UserName }}@{{ .HostName }}"
      - type: path
        template: " {{ .Path }} "
        foreground: "p:pine"
        properties:
          home_icon: "~"
          style: unique
        style: plain
      - type: git
        template: " {{ .UpstreamIcon }}  {{ .HEAD }} {{if .BranchStatus }}{{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} ï„ {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} ï† {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} ïƒ‡ {{ .StashCount }}{{ end }}"
        foreground: "p:foam"
        style: "plain"
        properties:
          fetch_status: true
          fetch_upstream_icon: true
          branch_icon: "îœ¥ "
          cherry_pick_icon: "îŠ› "
          commit_icon: "ï— "
          merge_icon: "îœ§ "
          no_commits_icon: "ïƒƒ "
          rebase_icon: "îœ¨ "
          revert_icon: "ïƒ¢ "
          tag_icon: "ï’ "
          mapped_branches:
            feat/*: "ğŸš€ "
            fix/*: "ğŸ› "
  - alignment: right
    type: prompt
    segments:
      - type: status
        foreground_templates:
          - "{{ if gt .Code 0 }}p:moon{{ end }}"
        template: " îˆº {{ .Code }} "
        style: plain
      - type: executiontime
        style: plain
        foreground: "p:gold"
        template: " î®¢ {{ .FormattedMs }} "
        properties:
          threshold: 500
          style: austin
          always_enabled: false
      - type: go
        style: plain
        foreground: "p:pine"
        template: " î˜§ {{ .Full }} "
      - type: rust
        style: plain
        foreground: "p:love"
        template: " î¨ {{ .Full }} "
      - type: zig
        style: plain
        foreground: "p:gold"
        template: " îš© {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
      - type: python
        style: plain
        foreground: "p:foam"
        template: " îˆµ {{ .Full }} "
      - type: kubectl
        style: plain
        foreground: "p:pine"
        template: " \U000F10FE {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "
  - alignment: left
    newline: true
    type: prompt
    segments:
      - type: text
        style: plain
        foreground: "p:text"
        template: " âˆ‡ "
tooltips:
  - type: gcp
    style: plain
    tips:
      - gcloud
      - gcp
    foreground: "p:gold"
    template: " î² {{.Project}} :: {{.Account}} "
final_space: true
version: 3
